package publictransportticketing;

import java.util.Arrays;

/**
 *
 * @author benp
 */
public class ManagementLoginUI extends javax.swing.JFrame {

    private final Server server;
    private final PublicTransportTicketing mainUi;

    /**
     * Creates new form FareFormUI
     * @param server
     * @param mainUi
     */
    public ManagementLoginUI(Server server, PublicTransportTicketing mainUi) {
        initComponents();
        this.server = server;
        this.mainUi = mainUi;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userIdInput = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        loginError = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userIdInput.setText("User ID");
        userIdInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userIdInputMouseClicked(evt);
            }
        });
        userIdInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userIdInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userIdInputFocusLost(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(204, 255, 204));
        loginButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        loginError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginError.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        passwordField.setText("password");
        passwordField.setEchoChar('\u2022');
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(0, 313, Short.MAX_VALUE))
                    .addComponent(loginError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(userIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginError, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        this.clearErrorMessage();
        String userId = this.userIdInput.getText();
        String password = String.copyValueOf(this.passwordField.getPassword());
        
        try {
            User user = this.server.getUser(userId, password);
        } catch (UserNotFoundException ex) {
            this.displayErrorMessage(ex.getMessage());
            return;
        } catch (WrongPasswordException ex) {
            this.displayErrorMessage(ex.getMessage());
            return;
        }
        
        this.setVisible(false);
        new ManagementUI(this.server, this).setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    void displayErrorMessage(String err) {
        this.loginError.setText(err);
    }
    
    void clearErrorMessage() {
        this.loginError.setText("");
    }
    
    private void userIdInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userIdInputMouseClicked
        if (this.userIdInput.getText().equals("User ID")) {
            this.userIdInput.setText("");
        }
    }//GEN-LAST:event_userIdInputMouseClicked

    private void userIdInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userIdInputFocusGained
        if (this.userIdInput.getText().equals("User ID")) {
            this.userIdInput.setText("");
        }
    }//GEN-LAST:event_userIdInputFocusGained

    private void userIdInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userIdInputFocusLost
       if (this.userIdInput.getText().equals("")) {
           this.userIdInput.setText("User ID");
       }
    }//GEN-LAST:event_userIdInputFocusLost

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        this.mainUi.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        char[] placeholder = {'p', 'a', 's', 's', 'w', 'o', 'r', 'd'};
        if (Arrays.equals(this.passwordField.getPassword(), placeholder)) {
            this.passwordField.setText("");
        }
    }//GEN-LAST:event_passwordFieldFocusGained

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        char[] empty = {};
        if (Arrays.equals(this.passwordField.getPassword(), empty)) {
            this.passwordField.setText("password");
        }
    }//GEN-LAST:event_passwordFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagementLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagementLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagementLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagementLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginError;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userIdInput;
    // End of variables declaration//GEN-END:variables
}
