/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package publictransportticketing;

import java.awt.CardLayout;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author rowellheria
 */
public class TerminalUI extends javax.swing.JFrame {
    
    private final CardLayout cardLayout;
    private Token validToken;
    private Token invalidToken;
    private Server server;
    /**
     * Creates new form TerminalUI
     */
    public TerminalUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        cardLayout = (CardLayout)panelTerminalScreen.getLayout();
        Account userAccount = this.createNewAccount();
        validToken = new Token(UniqueID.generate(), "CARD", userAccount.accountID);
        validToken.isValid = true;
        
        invalidToken = new Token(UniqueID.generate(), "CARD", userAccount.accountID);
        
        userAccount.tokenList.addToken(validToken);
        
        server = new Server();
        server.allAccounts.addAccount(userAccount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTerminalScreen = new javax.swing.JPanel();
        panelDefaultScreen = new javax.swing.JPanel();
        labelDefaultScreen = new javax.swing.JLabel();
        panelRetrieveDetailsScreen = new javax.swing.JPanel();
        labelRetrieveDetailsScreen = new javax.swing.JLabel();
        panelErrorScreen = new javax.swing.JPanel();
        labelErrorScreen = new javax.swing.JLabel();
        panelUserDetailsScreen = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonInsertCard = new javax.swing.JButton();
        buttonRemoveCard = new javax.swing.JButton();
        panelCoins = new javax.swing.JPanel();
        buttonTwoPounds = new javax.swing.JButton();
        buttonOnePounds = new javax.swing.JButton();
        buttonFiftyPence = new javax.swing.JButton();
        buttonTwentyPence = new javax.swing.JButton();
        buttonTenPence = new javax.swing.JButton();
        checkBoxInvalidToken = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Terminal");
        setResizable(false);

        panelTerminalScreen.setLayout(new java.awt.CardLayout());

        panelDefaultScreen.setBackground(new java.awt.Color(153, 204, 255));
        panelDefaultScreen.setName("panelDefaultScreen"); // NOI18N

        labelDefaultScreen.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelDefaultScreen.setForeground(new java.awt.Color(255, 255, 255));
        labelDefaultScreen.setText("Please insert your card below to begin");

        javax.swing.GroupLayout panelDefaultScreenLayout = new javax.swing.GroupLayout(panelDefaultScreen);
        panelDefaultScreen.setLayout(panelDefaultScreenLayout);
        panelDefaultScreenLayout.setHorizontalGroup(
            panelDefaultScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDefaultScreenLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(labelDefaultScreen)
                .addGap(97, 97, 97))
        );
        panelDefaultScreenLayout.setVerticalGroup(
            panelDefaultScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDefaultScreenLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(labelDefaultScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        panelTerminalScreen.add(panelDefaultScreen, "panelDefaultScreen");

        panelRetrieveDetailsScreen.setBackground(new java.awt.Color(255, 255, 255));
        panelRetrieveDetailsScreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        panelRetrieveDetailsScreen.setName("panelRetrieveDetailsScreen"); // NOI18N

        labelRetrieveDetailsScreen.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelRetrieveDetailsScreen.setText("Retrieving Account Details");

        javax.swing.GroupLayout panelRetrieveDetailsScreenLayout = new javax.swing.GroupLayout(panelRetrieveDetailsScreen);
        panelRetrieveDetailsScreen.setLayout(panelRetrieveDetailsScreenLayout);
        panelRetrieveDetailsScreenLayout.setHorizontalGroup(
            panelRetrieveDetailsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRetrieveDetailsScreenLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(labelRetrieveDetailsScreen)
                .addGap(142, 142, 142))
        );
        panelRetrieveDetailsScreenLayout.setVerticalGroup(
            panelRetrieveDetailsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRetrieveDetailsScreenLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(labelRetrieveDetailsScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        panelTerminalScreen.add(panelRetrieveDetailsScreen, "panelRetrieveDetailsScreen");

        panelErrorScreen.setBackground(new java.awt.Color(255, 204, 204));
        panelErrorScreen.setName("panelErrorScreen"); // NOI18N

        labelErrorScreen.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelErrorScreen.setForeground(new java.awt.Color(204, 0, 0));
        labelErrorScreen.setText("Invalid Token");

        javax.swing.GroupLayout panelErrorScreenLayout = new javax.swing.GroupLayout(panelErrorScreen);
        panelErrorScreen.setLayout(panelErrorScreenLayout);
        panelErrorScreenLayout.setHorizontalGroup(
            panelErrorScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelErrorScreenLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(labelErrorScreen)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        panelErrorScreenLayout.setVerticalGroup(
            panelErrorScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelErrorScreenLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(labelErrorScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        panelTerminalScreen.add(panelErrorScreen, "panelErrorScreen");

        panelUserDetailsScreen.setBackground(new java.awt.Color(204, 204, 204));
        panelUserDetailsScreen.setName("panelUserDetailsScreen"); // NOI18N

        javax.swing.GroupLayout panelUserDetailsScreenLayout = new javax.swing.GroupLayout(panelUserDetailsScreen);
        panelUserDetailsScreen.setLayout(panelUserDetailsScreenLayout);
        panelUserDetailsScreenLayout.setHorizontalGroup(
            panelUserDetailsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        panelUserDetailsScreenLayout.setVerticalGroup(
            panelUserDetailsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        panelTerminalScreen.add(panelUserDetailsScreen, "panelUserDetailsScreen");

        buttonInsertCard.setText("Insert Card");
        buttonInsertCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertCardActionPerformed(evt);
            }
        });

        buttonRemoveCard.setText("Remove Card");
        buttonRemoveCard.setEnabled(false);
        buttonRemoveCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveCardActionPerformed(evt);
            }
        });

        buttonTwoPounds.setText("£2");
        buttonTwoPounds.setEnabled(false);

        buttonOnePounds.setText("£1");
        buttonOnePounds.setEnabled(false);

        buttonFiftyPence.setText("50p");
        buttonFiftyPence.setEnabled(false);

        buttonTwentyPence.setText("20p");
        buttonTwentyPence.setEnabled(false);

        buttonTenPence.setText("10p");
        buttonTenPence.setEnabled(false);

        javax.swing.GroupLayout panelCoinsLayout = new javax.swing.GroupLayout(panelCoins);
        panelCoins.setLayout(panelCoinsLayout);
        panelCoinsLayout.setHorizontalGroup(
            panelCoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoinsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonTenPence, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelCoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buttonFiftyPence, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(buttonTwoPounds, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOnePounds, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTwentyPence, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCoinsLayout.setVerticalGroup(
            panelCoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoinsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTwoPounds)
                    .addComponent(buttonOnePounds))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFiftyPence)
                    .addComponent(buttonTwentyPence))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonTenPence)
                .addContainerGap())
        );

        checkBoxInvalidToken.setText("Invalid Token");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonRemoveCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(checkBoxInvalidToken)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonInsertCard, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(panelTerminalScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(panelTerminalScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonInsertCard)
                            .addComponent(checkBoxInvalidToken))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonRemoveCard)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCoins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInsertCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertCardActionPerformed
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            public void run() {
                retrieveTokenDetails();
            }
        }, 2000);
        
        cardLayout.show(panelTerminalScreen, panelRetrieveDetailsScreen.getName());
        
        buttonInsertCard.setEnabled(false);
        buttonRemoveCard.setEnabled(true);
    }//GEN-LAST:event_buttonInsertCardActionPerformed

    private void buttonRemoveCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveCardActionPerformed
        cardLayout.first(panelTerminalScreen);
        
        buttonInsertCard.setEnabled(true);
        buttonRemoveCard.setEnabled(false);
        toggleCoinButtons(false);
    }//GEN-LAST:event_buttonRemoveCardActionPerformed

    private void retrieveTokenDetails() {
        Token tokenToUse = checkBoxInvalidToken.isSelected() 
                ? invalidToken
                : validToken;
        
        String accountId = tokenToUse.getAccountID();
        Account account = server.findAccount(accountId);
        
        if (account != null) {
            Boolean isTokenValid = server.validateToken(account, tokenToUse);
            
            if (isTokenValid) {
                cardLayout.show(panelTerminalScreen, panelUserDetailsScreen.getName());
                
                toggleCoinButtons(true);
            } else {
                cardLayout.show(panelTerminalScreen, panelErrorScreen.getName());
            }
        } else {
            cardLayout.show(panelTerminalScreen, panelErrorScreen.getName());
        }
    }
    
    private Account createNewAccount() {
        Account account = new Account();
        account.accountID = UniqueID.generate();
        account.accountName = "SAMPLE_ACCOUNT_NAME";
        
        return account;
    }
    
    private void toggleCoinButtons(Boolean enabled) {
        buttonFiftyPence.setEnabled(enabled);
        buttonInsertCard.setEnabled(enabled);
        buttonOnePounds.setEnabled(enabled);
        buttonRemoveCard.setEnabled(enabled);
        buttonTenPence.setEnabled(enabled);
        buttonTwentyPence.setEnabled(enabled);
        buttonTwoPounds.setEnabled(enabled);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TerminalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TerminalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TerminalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TerminalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TerminalUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFiftyPence;
    private javax.swing.JButton buttonInsertCard;
    private javax.swing.JButton buttonOnePounds;
    private javax.swing.JButton buttonRemoveCard;
    private javax.swing.JButton buttonTenPence;
    private javax.swing.JButton buttonTwentyPence;
    private javax.swing.JButton buttonTwoPounds;
    private javax.swing.JCheckBox checkBoxInvalidToken;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDefaultScreen;
    private javax.swing.JLabel labelErrorScreen;
    private javax.swing.JLabel labelRetrieveDetailsScreen;
    private javax.swing.JPanel panelCoins;
    private javax.swing.JPanel panelDefaultScreen;
    private javax.swing.JPanel panelErrorScreen;
    private javax.swing.JPanel panelRetrieveDetailsScreen;
    private javax.swing.JPanel panelTerminalScreen;
    private javax.swing.JPanel panelUserDetailsScreen;
    // End of variables declaration//GEN-END:variables
}
